### ISSUE TITLE
Determine Software Feature Plan

### ISSUE THREAD

**Issue by orvis-ec-pr** [ManchesterMachineMakers/RobotController#47]
Determine what features our software needs, based on the challenge at hand.  Include new members in this discussion!

- Review past seasons' needs
- - diagnostics
- - vision
- - localization/navigation
- - precision control of motors
- - servo control
- - lighting
- - training of new programmers

- Create project items for each need and/or logical step.

**Comment by MilesVernon** [comment]
diagnostics: Aleks is the expert here, but I've never used any of the systems set up
vision: we will need and use this for aprilTag processing
localization/navigation: for now, we've decided on the sparkfun OTOS and pedropathing
precision control of motors: TBD
servo control: with servo.setPosition()?
lighting: TBD, but not urgent at all
training of new programmers: Important, but not necessary at this point in time. I'm having trouble finding time to train programmers.

**Comment by aleksrutins** [comment]
I can help train new programmers.

**Comment by MilesVernon** [comment]
Update:

diagnostics: no (unless convinced otherwise)
vision: we will need and use this for apirlTag processing
localization: sparkfun OTOS/aprilTags
navigation: pedro pathing
precision control of motors: not needed for driveBase, can be looked into for other subasseblies
servo control: servos don't really need PID
lighting: it's quick to set up, we can decide later in the season. Be careful of battery consumption
training of new programmers: sure
