### ISSUE TITLE
Chassis Design

### ISSUE THREAD

**Issue by orvis-ec-pr** [ManchesterMachineMakers/RobotController#49]
Suggestion: we use the design from GoBilda's Robot in 3 Days to start with.  They are putting out a full bill of materials, and I believe that the chassis fits our needs for something compact.

**Comment by aleksrutins** [comment]
I've started working on some CAD [here](https://cad.onshape.com/documents/a8854c9ade65f3a213cde405/w/37dafb6388eb0995d808cc46/e/f046ead7fc7fc36ccbf4153f) (shared with the main team account, ping me if you want access), but I'm waiting to get access to the FTC parts library before I put in motors.

A couple of different routes we can go with this design, since the current side channels in it can only fit one motor each:
1. Lengthen the chassis and do a bevel gear mecanum drive, as usual.
2. Keep the chassis short as is and do a tank drive, with one motor per side.

Which one sounds better to y'all? I'm willing to model both so that we can compare them.

**Comment by orvis-ec-pr** [comment]
You don't need to lengthen the chassis if you mount the motors vertically, as we did with Freya.  However, if you want a mecanum drive I'll note that the wheelbase as it is isn't square, as the frame itself is square.  The chassis will end up wide, so you can definitely afford to lengthen the frame.

Having fewer motors does make the bot lighter to lift, but I think we need to do a full points analysis before deciding our primary goals. 

The starter bot uses a tank drive: https://www.gobilda.com/ftc-starter-bot-resource-guide-into-the-deep/
Though their Ri3D is mecanum for strafing.
